sensor:
  - platform: adc
    pin: GPIO0
    attenuation: auto
    id: battery_voltage
    name: "${friendly_name} Battery Voltage"
    update_interval: never
    filters:
      - multiply: 2.0

  - platform: copy
    source_id: battery_voltage
    name: "${friendly_name} Battery"
    device_class: battery
    unit_of_measurement: "%"
    filters:
      - calibrate_linear:
          method: exact
          datapoints:
            - 3.30 -> 0
            - 3.50 -> 5
            - 3.60 -> 10
            - 3.70 -> 25
            - 3.80 -> 45
            - 3.90 -> 65
            - 4.00 -> 85
            - 4.10 -> 100
      - clamp:
          min_value: 0
          max_value: 100