i2c:
  sda: GPIO22
  scl: GPIO23
  scan: false

sensor:
  - platform: shtcx
    id: shtc3_sensor
    temperature:
      name: "${friendly_name} Temperature"
    humidity:
      name: "${friendly_name} Humidity"
    update_interval: never