deep_sleep:
  id: deep_sleep_control
  sleep_duration: 15min

switch:
  - platform: template
    name: "${friendly_name} Deep Sleep Enabled"
    id: deep_sleep_enabled
    optimistic: true
    restore_mode: ALWAYS_OFF

    turn_on_action:
      - script.execute: update_and_sleep

script:
  - id: update_sensors
    mode: restart
    then:
      - component.update: shtc3_sensor
      - component.update: battery_voltage
      - component.update: wifi_rssi

  - id: update_and_sleep
    mode: single
    then:
      - logger.log: "Updating sensors before sleep."
      - script.execute: update_sensors
      - script.wait: update_sensors

      # Give the measurements and API states time to be transmitted.
      - delay: 2s

      - if:
          condition:
            switch.is_on: deep_sleep_enabled
          then:
            - logger.log: "Entering deep sleep."
            - deep_sleep.enter: deep_sleep_control

esphome:
  on_boot:
    priority: -100
    then:
      - if:
          condition:
            lambda: |-
              return esp_sleep_get_wakeup_cause() == ESP_SLEEP_WAKEUP_TIMER;
          then:
            - logger.log: "Timer wake-up detected."

            - switch.template.publish:
                id: deep_sleep_enabled
                state: ON

            - wait_until:
                condition:
                  api.connected:
                timeout: 30s

            - if:
                condition:
                  api.connected:
                then:
                  - logger.log: "Home Assistant connected."
                  - script.execute: update_and_sleep
                else:
                  - logger.log: "API connection timeout; returning to sleep."
                  - deep_sleep.enter: deep_sleep_control

          else:
            - logger.log: "Power-on or reset: deep sleep disabled."

            - switch.template.publish:
                id: deep_sleep_enabled
                state: OFF

            - wait_until:
                condition:
                  api.connected:
                timeout: 30s

            - if:
                condition:
                  api.connected:
                then:
                  - script.execute: update_sensors

interval:
  - interval: 5s
    then:
      - if:
          condition:
            switch.is_off: deep_sleep_enabled
          then:
            - script.execute: update_sensors