deep_sleep:
  id: deep_sleep_control
  sleep_duration: 15min

switch:
  - platform: template
    name: "${friendly_name} Deep Sleep Enabled"
    id: deep_sleep_enabled
    optimistic: true
    restore_mode: ALWAYS_OFF

esphome:
  on_boot:
    priority: -100
    then:
      - if:
          condition:
            lambda: |-
              return esp_sleep_get_wakeup_cause() == ESP_SLEEP_WAKEUP_TIMER;
          then:
            - logger.log: "Timer wake-up: deep sleep remains enabled."
            - switch.turn_on: deep_sleep_enabled
          else:
            - logger.log: "Power-on or reset: deep sleep disabled."

api:
  on_client_connected:
    then:
      - component.update: shtc3_sensor
      - component.update: battery_voltage
      - component.update: wifi_rssi

      - if:
          condition:
            switch.is_on: deep_sleep_enabled
          then:
            - delay: 500ms
            - deep_sleep.enter: deep_sleep_control